{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "appname.serviceAccountName" . }}
  labels:
{{ include "appname.labels" . | nindent 4 }}
{{- end -}}
